name: Testing Self-Hosted Runner
on:
    workflow_dispatch: 

jobs:
    testing:
        runs-on: [self-hosted, Linux, rohan-kk]
        steps:
          - name: Echo Content
            run: |
              echo Ok
              sleep 15s